# Generated by Django 3.0 on 2020-05-31 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackinfo2', '0005_auto_20200601_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='password11',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='user',
            new_name='username',
        ),
    ]
