# Generated by Django 3.0 on 2020-05-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('clg', models.CharField(max_length=300)),
                ('gen', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('github', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
