# Generated by Django 3.0 on 2020-05-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdetail',
            old_name='clg',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='signupdetail',
            old_name='gen',
            new_name='gender',
        ),
    ]
