# Generated by Django 3.0 on 2020-05-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackinfo', '0002_auto_20200531_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderDetail',
            fields=[
                ('teamname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('statusid', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('college', models.CharField(max_length=300)),
                ('yearofstudy', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=40)),
                ('github', models.URLField(default='', max_length=250)),
                ('linkedin', models.URLField(default='', max_length=250)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('college', models.CharField(max_length=300)),
                ('yearofstudy', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=40)),
                ('github', models.URLField(default='', max_length=250)),
                ('linkedin', models.URLField(default='', max_length=250)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='signupdetail',
            name='github',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='signupdetail',
            name='linkedin',
            field=models.URLField(default='', max_length=250),
        ),
    ]
