# Generated by Django 3.0 on 2020-05-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackinfo', '0003_auto_20200531_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdetail',
            name='branch1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='college1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='contact1',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='email1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='firstname1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='gender1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='github1',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='lastname1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='linkedin1',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='teamdetail',
            name='yearofstudy1',
            field=models.CharField(default='', max_length=10),
        ),
    ]
