# Generated by Django 3.0 on 2020-05-31 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackinfo', '0004_auto_20200531_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdetail',
            name='contact1',
        ),
    ]
