# Generated by Django 3.0 on 2020-05-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackinfo', '0007_auto_20200531_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberdetail',
            name='contact1',
        ),
    ]
