# Generated by Django 3.0 on 2020-05-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackinfo', '0008_remove_teammemberdetail_contact1'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberdetail',
            name='phone1',
            field=models.CharField(default='', max_length=15),
        ),
    ]
